create table if not exists notification_history (
    id bigint generated by default as identity primary key,
    line_user_id varchar(255) not null,
    notification_type varchar(80) not null,
    summary varchar(500) not null,
    delivery_status varchar(20) not null default 'SENT',
    sent_at timestamp with time zone not null default current_timestamp
);

create index if not exists idx_notification_history_user_sent
    on notification_history(line_user_id, sent_at desc, id desc);
