create table if not exists expenses (
    id bigint generated by default as identity primary key,
    line_user_id varchar(128) not null references benly_users(line_user_id) on delete cascade,
    amount integer not null check (amount > 0),
    description varchar(500) not null,
    category varchar(40) not null default 'その他',
    spent_on date not null,
    created_at timestamp with time zone not null default current_timestamp,
    updated_at timestamp with time zone not null default current_timestamp
);

create index if not exists idx_expenses_user_date
    on expenses(line_user_id, spent_on desc, id desc);
create index if not exists idx_expenses_user_category
    on expenses(line_user_id, category, spent_on desc);
