create table if not exists habits (
    id bigint generated by default as identity primary key,
    line_user_id varchar(128) not null references benly_users(line_user_id) on delete cascade,
    name varchar(300) not null,
    active_days varchar(7) not null default '1234567',
    reminder_time time,
    active boolean not null default true,
    created_at timestamp with time zone not null default current_timestamp,
    updated_at timestamp with time zone not null default current_timestamp
);

create table if not exists habit_completions (
    id bigint generated by default as identity primary key,
    habit_id bigint not null references habits(id) on delete cascade,
    line_user_id varchar(128) not null references benly_users(line_user_id) on delete cascade,
    completed_on date not null,
    completed_at timestamp with time zone not null default current_timestamp,
    unique(habit_id, completed_on)
);

create index if not exists idx_habits_user_active
    on habits(line_user_id, active, id);
create index if not exists idx_habits_reminder
    on habits(active, reminder_time);
create index if not exists idx_habit_completions_user_date
    on habit_completions(line_user_id, completed_on desc);
