create table if not exists benly_users (
    line_user_id varchar(128) primary key,
    display_name varchar(120),
    experience integer not null default 0,
    streak_days integer not null default 0,
    created_at timestamp with time zone not null default current_timestamp,
    updated_at timestamp with time zone not null default current_timestamp
);

create table if not exists memos (
    id bigint generated by default as identity primary key,
    line_user_id varchar(128) not null references benly_users(line_user_id) on delete cascade,
    content text not null,
    memo_type varchar(30) not null default 'TEXT',
    source_url text,
    latitude decimal(10,7),
    longitude decimal(10,7),
    archived boolean not null default false,
    created_at timestamp with time zone not null default current_timestamp
);
create index if not exists idx_memos_user_created on memos(line_user_id, created_at desc);

create table if not exists tasks (
    id bigint generated by default as identity primary key,
    line_user_id varchar(128) not null references benly_users(line_user_id) on delete cascade,
    title varchar(500) not null,
    priority varchar(10) not null default 'MEDIUM',
    due_at timestamp with time zone,
    completed boolean not null default false,
    completed_at timestamp with time zone,
    postpone_count integer not null default 0,
    created_at timestamp with time zone not null default current_timestamp
);
create index if not exists idx_tasks_user_status on tasks(line_user_id, completed, due_at);

create table if not exists shopping_items (
    id bigint generated by default as identity primary key,
    line_user_id varchar(128) not null references benly_users(line_user_id) on delete cascade,
    name varchar(300) not null,
    quantity varchar(80),
    category varchar(80),
    store varchar(120),
    purchased boolean not null default false,
    purchased_at timestamp with time zone,
    created_at timestamp with time zone not null default current_timestamp
);
create index if not exists idx_shopping_user_status on shopping_items(line_user_id, purchased, created_at);

create table if not exists schedules (
    id bigint generated by default as identity primary key,
    line_user_id varchar(128) not null references benly_users(line_user_id) on delete cascade,
    title varchar(500) not null,
    starts_at timestamp with time zone not null,
    ends_at timestamp with time zone,
    source varchar(30) not null default 'BENLY',
    completed boolean not null default false,
    created_at timestamp with time zone not null default current_timestamp
);
create index if not exists idx_schedules_user_start on schedules(line_user_id, starts_at);

create table if not exists user_settings (
    line_user_id varchar(128) primary key references benly_users(line_user_id) on delete cascade,
    morning_notification_time varchar(5) not null default '06:00',
    weather_location varchar(200) not null default 'Tokyo',
    weather_enabled boolean not null default true,
    morning_brief_enabled boolean not null default true,
    experience_display_enabled boolean not null default true,
    updated_at timestamp with time zone not null default current_timestamp
);

create table if not exists experience_logs (
    id bigint generated by default as identity primary key,
    line_user_id varchar(128) not null references benly_users(line_user_id) on delete cascade,
    points integer not null,
    reason varchar(120) not null,
    created_at timestamp with time zone not null default current_timestamp
);
