ALTER TABLE memos ADD COLUMN IF NOT EXISTS favorite BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE memos ADD COLUMN IF NOT EXISTS tags VARCHAR(500);
ALTER TABLE memos ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP;
